# docker-compose.yml
---
version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            back-tier:
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_CREATE_TOPICS: "test:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ZOOKEEPER_TIMEOUT_MS: 36000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            back-tier:
networks:
  back-tier: