// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Content
	Message
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Content struct {
	Header string `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Body   string `protobuf:"bytes,2,opt,name=Body" json:"Body,omitempty"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Content) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *Content) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Message struct {
	From    string   `protobuf:"bytes,1,opt,name=From" json:"From,omitempty"`
	Content *Content `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Content)(nil), "message.Content")
	proto.RegisterType((*Message)(nil), "message.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x4c, 0xb9,
	0xd8, 0x9d, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x84, 0xc4, 0xb8, 0xd8, 0x3c, 0x52, 0x13, 0x53,
	0x52, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x21, 0x21, 0x2e, 0x16, 0xa7,
	0xfc, 0x94, 0x4a, 0x09, 0x26, 0xb0, 0x28, 0x98, 0xad, 0xe4, 0xc9, 0xc5, 0xee, 0x0b, 0x31, 0x01,
	0x24, 0xed, 0x56, 0x94, 0x9f, 0x0b, 0xd5, 0x04, 0x66, 0x0b, 0x69, 0xc1, 0x4d, 0x05, 0xeb, 0xe2,
	0x36, 0x12, 0xd0, 0x83, 0xd9, 0x0f, 0x15, 0x0f, 0x82, 0x29, 0x48, 0x62, 0x03, 0xbb, 0xc8, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xe3, 0xe3, 0x0e, 0xa2, 0x00, 0x00, 0x00,
}
